/**
 * Flashcard Model
 * 
 * Represent a single Flashcard generated by the system.
 * 
 * Each flashcard belongs to a FlashcardSet and is tied to a resource:
 * - Workspace
 * - Folder
 * - File
 * 
 * This model also stores space-repetition information metadata (interval, difficulty, etc).
 */

import mongoose, { Schema, Document, Types } from "mongoose";

/**
 * Flashcard interface used for Typescript and schema typing.
 */
export interface Flashcard{ 
    question: string;
    answer: string;
    type: "question-answer" | "fill-in-the-blank" | "mcq";
    options?: string[]; //for mcq

    parentSetId?: Types.ObjectId | string; //link back to Flashcardset
    resourceId: Types.ObjectId | string; //workspace/folder/file
    resourceType: "Workspace" | "Folder" | "File";

    // Spaced Repetition
    interval: number; //days till next review
    difficulty: number; //how easy/difficult the card is (easeFactor)
    repetition: number; //number of successful reviews
    dueDate: Date;
    lastReviewed?: Date;

    createdBy: Types.ObjectId | string; 
    createdFor: string;
    updatedAt: Date;
    source: {
        fileIds: string[];
        blockIds: string[];
        startBlockId?: string;
        endBlockId?: string;
        blocksState: Record<string, {
            updatedAt: Date;
        }>;
    },
}
const SourceSchema = new Schema({
     fileIds: [{
        type: Schema.Types.ObjectId,
        ref: "File",
        required: true,
       }],
       blockIds:[{
        type: String,
        required: true,
       }],
       startBlockId: String,
       endBlockId: String,
       blocksState: {
        type: Map,
        of: new Schema({
            updatedAt: {
                type: Date,
                required: true,
            },
        }, { _id: false }),
        required: true,
       }
}, { _id: false});
/**
 *  Flashcard Schema
 * Defines database fields and validation.
 */
export const FlashcardSchema: Schema<Flashcard> = new Schema({
   question: {
       type: String,
       required: true,
   },
   answer: {
       type: String,
       required: true,
   },
   type: {
       type: String,
       required: true,
   },
   options: {
       type: [String],
   },
   parentSetId: {
       type: mongoose.Schema.Types.ObjectId,
       required: false,
       ref: "FlashcardSet",
   },
   resourceId: {
       type: mongoose.Schema.Types.ObjectId,
       required: true,
   },
   resourceType: {
       type: String,
       required: true,
   },
   interval: {
       type: Number,
      default: 1,
   },
   difficulty: {
       type: Number,
      default: 2.5,
   },
   repetition: {
       type: Number,
      default: 0,
   },
   dueDate: {
       type: Date,
       default: () => new Date(),
   },
   lastReviewed: {
       type: Date,
       default: null
   },
   createdBy: {
       type: mongoose.Schema.Types.ObjectId,
       required: true,
       ref: "User",
   },
   createdFor: {
       type: String,
    //    required: true,
   },
   source: {
      type: SourceSchema,
      required: true
   }
}, { timestamps: true });
